files:
    cars: C:\\Users\\1\\Desktop\\cars.txt
    models: C:\\Users\\1\\Desktop\\models.txt
    brands: C:\\Users\\1\\Desktop\\brands.txt

hibernate:
    configuration: src/main/resources/postgresql.yml