spring:
    datasource:
        url: jdbc:h2:mem:database;MODE=PostgreSQL;DB_CLOSE_DELAY=-1  #;DATABASE_TO_UPPER=false
        username: postgres
        password: password
        driver: org.h2.Driver
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration/h2
    logging:
        level:
            org.flywaydb: DEBUG
